fetch-info: fetch-info.o
	$(CC) -o fetch-info fetch-info.o
fetch-info.o: fetch-info.c
	$(CC) -c fetch-info.c
pipe4: pipe4.o
	$(CC) -o pipe4 pipe4.o
pipe4.o: pipe4.c
	$(CC) -c pipe4.c
clean:
	rm -f fetch-info
	rm -f pipe4
	rm -f *.o